### PR TITLE
⚠️ Disallow bundles with dependencies and constraints

### LINKED ISSUE #779: Fail installation attempts for registry+v1 bundles with expressed dependencies

### PR DESCRIPTION
**Pull request by m1kola**
# Description

Draft for the changes proposed in [this doc](https://docs.google.com/document/d/1Bwhv00KtFfB5JQ_11JAN00YnyehzGPIyYb3mdnc9GxM/edit): disallowing registry+v1 bundles with dependencies.

Closes #779

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

File: internal/controllers/clusterextension_controller.go [hunk 1]
```diff
@@ -219,6 +227,33 @@ func (r *ClusterExtensionReconciler) variables(ctx context.Context) ([]deppy.Var
...
+	if err != nil {
+		return fmt.Errorf("unable to determine type of bundle %q: %s", bundle.Name, err)
+	}
+
+	if mediaType != catalogmetadata.MediaTypeRegistry {
+		// We only validate registry+v1 bundles
+		return nil
+	}
+
+	dependencyPropertyTypes := []string{property.TypePackageRequired, property.TypeGVKRequired, "olm.constraint"}
```
Comment (m1kola) [inline internal/controllers/clusterextension_controller.go:241]: Find a constant for `"olm.constraint"`.

File: internal/controllers/clusterextension_controller.go [hunk 2]
```diff
@@ -165,6 +166,13 @@ func (r *ClusterExtensionReconciler) reconcile(ctx context.Context, ext *ocv1alp
 		setDeprecationStatusesUnknown(&ext.Status.Conditions, "deprecation checks have not been attempted as installation has failed", ext.GetGeneration())
 		return ctrl.Result{}, err
 	}
+
+	if err := r.validateBundle(bundle); err != nil {
```
Comment (m1kola) [inline internal/controllers/clusterextension_controller.go:170]: 1. Need tests
2. Need to find a real world example of `"olm.constraint"` usage.

**Comment by grokspawn** [comment]
closes https://github.com/operator-framework/operator-controller/issues/734

File: internal/controllers/clusterextension_controller.go [hunk 3]
```diff
@@ -219,6 +227,33 @@ func (r *ClusterExtensionReconciler) variables(ctx context.Context) ([]deppy.Var
...
+		// We only validate registry+v1 bundles
+		return nil
+	}
+
+	dependencyPropertyTypes := []string{property.TypePackageRequired, property.TypeGVKRequired, "olm.constraint"}
+	for i := range bundle.Properties {
+		for _, propType := range dependencyPropertyTypes {
+			if bundle.Properties[i].Type == propType {
+				return fmt.Errorf(
+					"bundle %q has one a dependency declared via one of the properties: %s",
```
Comment (m1kola) [inline internal/controllers/clusterextension_controller.go:246]:
```suggestion
					"bundle %q has a dependency declared via one of the properties: %s",
```

File: internal/controllers/clusterextension_controller.go [hunk 4]
```diff
@@ -278,6 +286,36 @@ func (r *ClusterExtensionReconciler) installedBundle(ctx context.Context, allBun
...
+func (r *ClusterExtensionReconciler) validateBundle(bundle *catalogmetadata.Bundle) error {
+	mediaType, err := bundle.MediaType()
+	if err != nil {
+		return fmt.Errorf("unable to determine type of bundle %q: %s", bundle.Name, err)
+	}
+
+	if mediaType != catalogmetadata.MediaTypeRegistry {
+		// We only validate registry+v1 bundles
+		return nil
+	}
```
Comment (m1kola) [inline internal/controllers/clusterextension_controller.go:298]: Wondering if we actually want to have this check... Maybe we should just disallow any bundles that express dependencies?

Comment (m1kola) [reply internal/controllers/clusterextension_controller.go:298]: > Is it possible for a simple bundle to express dependencies?

Do you mean `plain+v0`? I'm not 100% sure, but I think they can have all the FBC properties.

Comment (grokspawn) [reply internal/controllers/clusterextension_controller.go:298]: I thought `plain+v0` were bare manifests, so would not present with an `olm.bundle` and properties like FBC, right?

Comment (m1kola) [reply internal/controllers/clusterextension_controller.go:298]: The bundle itself is bare manifests, but the catalog will still have metadata. For example, take a look at [this demo](https://github.com/operator-framework/operator-controller/blob/main/docs/demos/coast-to-coast-q4-2023.md#create-an-initial-file-based-catalog-fbc-image).

Or am I missing something?

Comment (grokspawn) [reply internal/controllers/clusterextension_controller.go:298]: You're good.   I forgot that there is still FBC associated with it, and that the v1-only `olm.bundle.mediatype` property is exercised to determine (and all my time up to now has been in v0 catalogs). 

In that case, you've talked me into it: I'd support either expanding this to remove the conditional and add tests, or handling plain+v0 bundles in a follow-up PR.

Comment (everettraven) [reply internal/controllers/clusterextension_controller.go:298]: My understanding is the same as @m1kola 

The bundle media type in this case is, IMO, unnecessary to consider and should instead assume that the input is valid FBC and therefore evaluate only the FBC contents for validation

Comment (everettraven) [reply internal/controllers/clusterextension_controller.go:298]: Although if I am misunderstanding the intention of this PR and the goal is to enforce that only `registry+v1` bundles will ever be allowed then adding a constraint to the validation to reject any other bundle media type

File: internal/controllers/clusterextension_controller.go [hunk 5]
```diff
@@ -278,6 +286,36 @@ func (r *ClusterExtensionReconciler) installedBundle(ctx context.Context, allBun
...
+
+	for i := range bundle.Properties {
+		for _, propType := range []string{
+			property.TypePackageRequired,
+			property.TypeGVKRequired,
+			property.TypeConstraint,
+		} {
```
Comment (everettraven) [inline internal/controllers/clusterextension_controller.go:305]: Could we instead make this a map and see if the bundle property type exists in the map we return the error?

This might be a premature and low-value optimization, but it reduces the time complexity from O(n*m) to O(n) (where n is the number of bundle properties and m is the unsupported properties) and is, IMO, easier to read

Comment (everettraven) [reply internal/controllers/clusterextension_controller.go:305]: This also might be a good use of the `sets` package since we really only care about the key (property type) and not the value in the map.

File: internal/controllers/clusterextension_controller.go (hunk 4 above)
Comment (everettraven) [reply internal/controllers/clusterextension_controller.go:298]: Another thing to note, the way the media type property was designed was such that registry+v1 bundles would not need to be changed. If the media type property does not exist it is assumed it is a registry+v1 bundle

File: internal/controllers/clusterextension_controller.go (hunk 5 above)
Comment (m1kola) [reply internal/controllers/clusterextension_controller.go:305]: @everettraven  I'm not a big fan of sets since they are just very slim wrapper around a no value map `map[T]struct{}{}`, but happy to switch to sets if people find it more clean. I'll do it in the next update.

> This might be a premature and low-value optimization, but it reduces the time complexity from O(n*m) to O(n)

Despite the nested loop this is considered O(n) since number of iterations in the inner loop is always 3 and does not depend on the input. Same as the following will be O(n):

```go
for i := range bundle.Properties {
	if bundle.Properties[i].Type == property.TypePackageRequired {
		return // ...
	}
	if bundle.Properties[i].Type == property.TypeGVKRequired {
		return // ...
	}
	if bundle.Properties[i].Type == property.TypeConstraint {
		return // ...
	}
}
```

File: internal/controllers/clusterextension_controller.go (hunk 4 above)
Comment (m1kola) [reply internal/controllers/clusterextension_controller.go]: After [this discussion](https://redhat-internal.slack.com/archives/C06KP34REFJ/p1714659939965849) in Slack we decided to get rid of the media type check. If any bundle installed via `ClusterExtension` be it `registry+v1` or `plain+v0` or whether else expresses any of the properties - we fail.

File: internal/controllers/clusterextension_controller.go (hunk 5 above)
Comment (everettraven) [reply internal/controllers/clusterextension_controller.go]: Fair enough on the time complexity. I guess I was approaching it from the perspective that the unsupported properties is an arbitrary value so while that is the case for this iteration it could shrink/grow as much or as little as we see fit. Using a map ensures that it is always an O(1) lookup.

**Review by everettraven — APPROVED** [review]
