### PR TITLE
⚠️ Remove `HasValidBundle` condition

### LINKED ISSUE #989: `ClusterExtension`'s condition `HasValidBundle` is `False` when `Resolved`, `Installed` and `Unpacked` are all `True`
It looks like something is wrong with `ClusterExtension`'s `HasValidBundle` condition. I noticed that in this test:
https://github.com/operator-framework/operator-controller/blob/cab41aaa6764f9413a58d52efe80dca9b8bdf651/test/e2e/cluster_extension_install_test.go#L82-L94

`HasValidBundle` reports `False` with the following message while other conditions such as `Resolved`, `Installed` and `Unpacked` are all report `True`:

```
error fetching bundles: error fetching catalog "test-catalog" contents: error performing request: Get "https://catalogd-catalogserver.olmv1-system.svc/catalogs/test-catalog/all.json": dial tcp 10.96.194.165:443: connect: connection refused
```

This can be reproduced by adding `spew.Dump(clusterExtension.Status.Conditions)` before this line:

https://github.com/operator-framework/operator-controller/blob/cab41aaa6764f9413a58d52efe80dca9b8bdf651/test/e2e/cluster_extension_install_test.go#L85

You should see something like this:

```
([]v1.Condition) (len=8 cap=9) {
 (v1.Condition) &Condition{Type:Resolved,Status:True,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:20 +0200 CEST,Reason:Success,Message:resolved to "docker-registry.operator-controller-e2e.svc.cluster.local:5000/bundles/registry-v1/prometheus-operator:v2.0.0",},
 (v1.Condition) &Condition{Type:Installed,Status:True,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:31 +0200 CEST,Reason:Success,Message:Instantiated bundle clusterextension-c75hzgnn successfully,},
 (v1.Condition) &Condition{Type:HasValidBundle,Status:False,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:20 +0200 CEST,Reason:ResolutionFailed,Message:error fetching bundles: error fetching catalog "test-catalog" contents: error performing request: Get "https://catalogd-catalogserver.olmv1-system.svc/catalogs/test-catalog/all.json": dial tcp 10.96.194.165:443: connect: connection refused,},
 (v1.Condition) &Condition{Type:Deprecated,Status:False,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:20 +0200 CEST,Reason:Deprecated,Message:,},
 (v1.Condition) &Condition{Type:PackageDeprecated,Status:False,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:20 +0200 CEST,Reason:Deprecated,Message:,},
 (v1.Condition) &Condition{Type:ChannelDeprecated,Status:False,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:20 +0200 CEST,Reason:Deprecated,Message:,},
 (v1.Condition) &Condition{Type:BundleDeprecated,Status:False,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:20 +0200 CEST,Reason:Deprecated,Message:,},
 (v1.Condition) &Condition{Type:Unpacked,Status:True,ObservedGeneration:1,LastTransitionTime:2024-06-28 11:19:20 +0200 CEST,Reason:UnpackSuccess,Message:unpack successful: ,}
}
```

Alternatively, modify the test with the following patch (apply on top of `main` which is currently at cab41aaa6764f9413a58d52efe80dca9b8bdf651):

```diff
diff --git a/test/e2e/cluster_extension_install_test.go b/test/e2e/cluster_extension_install_test.go
index 3308c03..23d31e1 100644
--- a/test/e2e/cluster_extension_install_test.go
+++ b/test/e2e/cluster_extension_install_test.go
@@ -117,6 +117,19 @@ func TestClusterExtensionInstallRegistry(t *testing.T) {
 		assert.Contains(ct, cond.Message, "Instantiated bundle")
 		assert.NotEmpty(ct, clusterExtension.Status.InstalledBundle)
 	}, pollDuration, pollInterval)
+
+	t.Log("By eventually reporting valid bundle")
+	require.EventuallyWithT(t, func(ct *assert.CollectT) {
+		assert.NoError(ct, c.Get(context.Background(), types.NamespacedName{Name: clusterExtension.Name}, clusterExtension))
+		cond := apimeta.FindStatusCondition(clusterExtension.Status.Conditions, ocv1alpha1.TypeHasValidBundle)
+		if !assert.NotNil(ct, cond) {
+			return
+		}
+		assert.Equal(ct, metav1.ConditionTrue, cond.Status)
+		assert.Equal(ct, ocv1alpha1.ReasonSuccess, cond.Reason)
+		assert.Empty(ct, cond.Message)
+		assert.NotEmpty(ct, clusterExtension.Status.InstalledBundle)
+	}, pollDuration, pollInterval)
 }
 
 func TestClusterExtensionInstallReResolvesWhenNewCatalog(t *testing.T) {
```

### PR DESCRIPTION
**Pull request by m1kola**
# Description

Closes #989 by removing the condition and solves an E2E flake.

Note: in [this brief](https://docs.google.com/document/d/1JWJxnDXM0X1JQ67ZIDx5j1ayb1d7ajrK_uSDDaz0G98/edit) were are revisiting `ClusterExtension` conditions and their reasons. [One of the points](https://docs.google.com/document/d/1JWJxnDXM0X1JQ67ZIDx5j1ayb1d7ajrK_uSDDaz0G98/edit#heading=h.l1ogecrfxz55) is about removal of `HasValidBundle` condition type.

The brief is still in review, but I would like to move forward with this change as it resolves a flake I hit regularly (especially locally).

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by m1kola** [comment]
go-apidiff is expected to fail because I'm chasing the API here.

File: test/e2e/cluster_extension_install_test.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func TestClusterExtensionInstallRegistry(t *testing.T) {
 	t.Log("By eventually reporting a successful resolution and bundle path")
 	require.EventuallyWithT(t, func(ct *assert.CollectT) {
 		assert.NoError(ct, c.Get(context.Background(), types.NamespacedName{Name: clusterExtension.Name}, clusterExtension))
-		assert.Len(ct, clusterExtension.Status.Conditions, 8)
+		assert.Len(ct, clusterExtension.Status.Conditions, 7)
```
Comment (bentito) [inline test/e2e/cluster_extension_install_test.go:85]: Not a comment on your need to change this, you need to, but this is bad for a couple reasons. 1) brittle test, 2) magic number in the code. 
Would we want to do something better at this point, maybe just checking for some of the Conditions having the statuses we care about rather than their count?

Comment (m1kola) [reply test/e2e/cluster_extension_install_test.go:85]: > Not a comment on your need to change this, you need to, but this is bad for a couple reasons. 1) brittle test, 2) magic number in the code.

Yes, I agree with this. But on the other hand - this line helped me spot the issue.

I think I can probably replace with something like 

```go
assert.Len(ct, clusterExtension.Status.Conditions, len(conditionsets.ConditionTypes))
```

Comment (bentito) [reply test/e2e/cluster_extension_install_test.go]: seems decent.

**Review by ankitathomas — APPROVED** [review]
/lgtm
