### PR TITLE
Fixes reading properties with the same type

### LINKED ISSUE #258: Ensure the FBC --> entity translation for bundle properties is not lossy
Currently the translation for catalog contents --> entity is lossy when it comes to bundle properties. As we can see from https://github.com/operator-framework/operator-controller/blob/80a5786d9a9335392d35e715b4956a93b9fd64c9/internal/resolution/entitysources/catalogdsource.go#L83-L90 we are only passing through bundle properties that are of type `olm.package` and therefore losing any other bundle property information.

We should update this to ensure that all bundle properties are being forwarded through during the entity translation so they can be used properly.

### PR DESCRIPTION
**Pull request by m1kola**
Some properties like `olm.package` only can appear in a bundle once and we currently handle this correctly.

However properties such as `olm.gvk` and `olm.gvk.required` can be present multiple times in the list. The current implementation overrides all the instances with the one which is the last in the list.

This modifies the code to be able to read in both cases.

Closes #258

# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

File: internal/catalogmetadata/types.go [hunk 1]
```diff
@@ -94,7 +94,7 @@ func (b *Bundle) loadRequiredPackages() error {
 	b.mu.Lock()
 	defer b.mu.Unlock()
 	if b.requiredPackages == nil {
-		requiredPackages, err := loadFromProps[[]PackageRequired](b, property.TypePackageRequired, false)
+		requiredPackages, err := loadOneFromProps[[]PackageRequired](b, property.TypePackageRequired, false)
```
Comment (joelanford) [inline internal/catalogmetadata/types.go:97]: Is this `olm.package.required`? If so, there can be multiple of these.

**Review by joelanford — APPROVED** [review]
