### PR TITLE
:bug: Use monorepo release for catalogd

### LINKED ISSUE #1605: Update the CatalogD demo script to use source-code in the operator-controller repo
See that we have the script: https://github.com/operator-framework/operator-controller/blob/main/catalogd/hack/scripts/demo-script.sh

We need to update it to the script from the operator-controller release instead.

PS: we might need to do a release with catalogD inside of the operator-controller to do this.

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
# Description

With the change we will use the operator-controller releases for catalogd demo script

Fixes  #1605

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Review by perdasilva — APPROVED** [review]

File: catalogd/hack/scripts/demo-script.sh [hunk 1]
```diff
@@ -12,7 +12,7 @@ kubectl cluster-info --context kind-kind
 sleep 10
 
 # use the install script from the latest github release
-curl -L -s https://github.com/operator-framework/catalogd/releases/latest/download/install.sh | bash
+curl -L -s https://github.com/operator-framework/operator-controller/releases/latest/download/install.sh | bash
```
Comment (rashmigottipati) [inline catalogd/hack/scripts/demo-script.sh:15]: As this change has been made before cutting a latest release, I think this link points to the old `latest` which does not include the monorepo changes. Is the plan to follow-up with cutting a release to make this script work?
